---
apiVersion: v1
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxSFVEOVM1QjYvQjAyN0FINFVDRU0vTWVIUjR2MzlaMnN0MG00bmxJd1AzU1No
kind: Secret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
