apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: wg-access-server
      version: "v0.4.6"
      sourceRef:
        kind: HelmRepository
        name: wireguard
        namespace: flux-system
      interval: 1m
  values:
    config:
      wireguard:
        externalHost: "<loadbalancer-ip>"

    # wg access server is an http server without TLS. Exposing it via a loadbalancer is NOT secure!
    # Uncomment the following section only if you are running on private network or simple testing.
    # A much better option would be TLS terminating ingress controller or reverse-proxy.
    web:
     service:
       type: "ClusterIP"
       config:
         adminUsername: "admin"
         adminPassword: "admin"
    wireguard:
      config:
        privateKey: "IM6n31ztV8bN+VA42BD08bAl0YRZxh+DhCpgmHD1WX8="
      service:
        type: "NodePort"

    persistence:
      enabled: false

