apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    git: https://github.com/istio/istio
    ref: 1.11.4
    path: manifests/charts/istio-operator
  values:
    hub: gcr.io/istio-release
    tag: 1.11.4