---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 1m
  url: https://github.com/istio/istio
  ref:
    tag: 1.12.1
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: manifests/charts/istio-operator
      version: '1.0.0'
      sourceRef:
        kind: GitRepository
        name: istio-operator
        namespace: istio-system
      interval: 1m
  values:
    hub: docker.io/querycapistio
    tag: 1.12.1