---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 1m
  url: https://github.com/istio/istio
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/charts/
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    name: istio-operator
    git: https://github.com/istio/istio
    path: manifests/charts/istio-operator
    ref: 1.12.1
  values:
    hub: gcr.io/istio-release
    tag: 1.12.1