---
- name: Initial Preparation
  gather_facts: true
  hosts: all
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
      become: true
      tags:
        - baseline

    - name: Update apt repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        autoclean: yes
        upgrade: full
      become: true
      tags:
        - baseline

    - name: Update all packages
      apt:
        name: "*"
        state: latest
      become: true
      tags:
        - baseline

    - name: Install the required packages
      apt:
        name: "libseccomp2"
        state: latest
      become: true
      tags:
        - baseline
  post_tasks:
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
      become: true

- name: Install K8s
  gather_facts: true
  hosts: all

  roles:
    - role: geerlingguy.containerd
      tags:
        - k8s
        - containerd
      become: true
      containerd_package: containerd

    - role: geerlingguy.kubernetes
      tags:
        - k8s
      become: true
